<a href="https://colab.research.google.com/github/sanchi23002/pytorch_projects_/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [4]:
df.shape

(569, 31)

**Test Train Split**



In [5]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

**Scaling of the features(X)**

In [6]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
x_test

array([[-0.21495915, -0.25524591, -0.24276299, ..., -0.55379085,
        -0.38799172, -0.99024322],
       [-0.06524652,  0.05271049, -0.05730827, ...,  1.03926187,
         0.46056103,  1.20905155],
       [-0.38162038, -1.41708141, -0.39785566, ...,  0.00583063,
        -0.88933227,  0.09630981],
       ...,
       [ 0.07316704,  1.3055331 ,  0.13512152, ...,  0.08272283,
         0.47411077,  1.03074541],
       [-0.40421852, -0.67751946, -0.45734888, ..., -0.86581942,
        -0.88763856, -1.09778411],
       [-0.15563905, -0.99014186, -0.17424322, ..., -0.14949163,
         0.81285439,  0.70087905]])

In [8]:
y_train

,diagnosis
339,M
326,B
40,M
550,B
497,B
...,...
7,M
12,M
277,M
134,M


In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**Numpy  array to pytorch tensor**

In [10]:
x_train = torch.from_numpy(x_train.astype(np.float32)) ## pytorch prefer float32 forcumputation of neural network
x_test = torch.from_numpy(x_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [11]:
print(x_train.shape)
print(y_train.shape)

torch.Size([455, 30])
torch.Size([455])


**Defining the model**

In [12]:
import torch.nn as nn

class NeuralNetwork(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)## it is a fully connected neuron , take all features as input and 1 output
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

**Important parameters**

In [13]:
learning_rate = 0.1
epoch = 100

**Loss function**

In [14]:
loss = nn.BCELoss()

**Training pipeline**

In [15]:
## always first create object(model)
model = NeuralNetwork(x_train.shape[1])

## defining optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate) ## batch gradient decent, w = w - n(x(i)*(ycap - y)) , b = b - n(ycap-y)

for i in range(epoch):
  y_pred = model(x_train)
  loss_found = loss(y_pred,y_train.view(-1,1))

  ##  gradient clearance
  optimizer.zero_grad()

  ## Backward Pass
  loss_found.backward()

  ##Parameter update
  optimizer.step()

  ## Print loss in each epoch.
  print("epoch",(i+1),"   loss: ",loss_found.item())


epoch 1    loss:  0.6298630833625793
epoch 2    loss:  0.5078755617141724
epoch 3    loss:  0.4357513189315796
epoch 4    loss:  0.3878803551197052
epoch 5    loss:  0.3535046875476837
epoch 6    loss:  0.32740646600723267
epoch 7    loss:  0.30676254630088806
epoch 8    loss:  0.2899150848388672
epoch 9    loss:  0.2758266031742096
epoch 10    loss:  0.26381421089172363
epoch 11    loss:  0.25340938568115234
epoch 12    loss:  0.24427951872348785
epoch 13    loss:  0.23618139326572418
epoch 14    loss:  0.22893273830413818
epoch 15    loss:  0.22239404916763306
epoch 16    loss:  0.21645627915859222
epoch 17    loss:  0.21103306114673615
epoch 18    loss:  0.2060547024011612
epoch 19    loss:  0.20146438479423523
epoch 20    loss:  0.19721512496471405
epoch 21    loss:  0.19326764345169067
epoch 22    loss:  0.18958884477615356
epoch 23    loss:  0.18615058064460754
epoch 24    loss:  0.182928666472435
epoch 25    loss:  0.17990221083164215
epoch 26    loss:  0.1770530343055725
epoch 

Evaluation

In [16]:
## Model Evaluation
with torch.no_grad():
  y_pred = model(x_test)
  y_pred = (y_pred>=0.5).float()
  accuracy = (y_pred==y_test).float().mean()
  print("accuracy" , accuracy.item())

accuracy 0.5646352767944336


**showing a custom project**

In [17]:
import torch
import torch.nn as nn

In [18]:
class my_model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3), ## index-->0
        nn.ReLU(),                 ## index-->1
        nn.Linear(3,1),            ## index-->2
        nn.Sigmoid()               ## index-->3
    )

  def forward(self,x):
    out = self.network(x)
    return out


In [19]:
## create dataset
x = torch.rand(100,10)
model2 = my_model(x.shape[1])

## call model for the forward pass
## model2.forward(x) ## can't change the forward function
model2(x)

tensor([[0.3872],
        [0.3818],
        [0.3904],
        [0.3465],
        [0.3538],
        [0.3618],
        [0.3574],
        [0.3685],
        [0.3763],
        [0.3787],
        [0.3555],
        [0.3604],
        [0.3724],
        [0.3583],
        [0.3559],
        [0.3743],
        [0.4049],
        [0.3880],
        [0.4085],
        [0.3750],
        [0.3654],
        [0.3575],
        [0.3763],
        [0.3857],
        [0.3656],
        [0.3727],
        [0.3928],
        [0.3642],
        [0.3553],
        [0.3766],
        [0.3838],
        [0.3662],
        [0.3620],
        [0.3894],
        [0.3626],
        [0.3874],
        [0.3973],
        [0.3499],
        [0.3368],
        [0.3578],
        [0.3798],
        [0.3839],
        [0.3753],
        [0.3334],
        [0.3932],
        [0.3637],
        [0.3849],
        [0.4022],
        [0.3757],
        [0.3663],
        [0.3642],
        [0.3595],
        [0.3773],
        [0.3823],
        [0.3307],
        [0

In [20]:
print(model2.network[0].weight)
print(model2.network[0].bias)
print(model2.network[2].weight)
print(model2.network[2].bias)

Parameter containing:
tensor([[ 0.1943,  0.2516, -0.0979, -0.0848, -0.1665,  0.2209,  0.2675, -0.2683,
          0.2141,  0.1020],
        [-0.0114,  0.1662, -0.1459, -0.0094, -0.2159, -0.2109,  0.2193,  0.0229,
          0.2420,  0.1137],
        [-0.0561, -0.0775, -0.1648, -0.1250, -0.0844,  0.1222,  0.1097,  0.1979,
          0.0885, -0.2351]], requires_grad=True)
Parameter containing:
tensor([0.2351, 0.1126, 0.0593], requires_grad=True)
Parameter containing:
tensor([[-0.4567,  0.4794,  0.2077]], requires_grad=True)
Parameter containing:
tensor([-0.3708], requires_grad=True)


In [21]:
!pip install torchinfo

In [22]:
from torchinfo import summary
Summary = summary(model2,x.shape)
print(Summary)

Layer (type:depth-idx)                   Output Shape              Param #
my_model                                 [100, 1]                  --
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 3]                  33
│    └─ReLU: 2-2                         [100, 3]                  --
│    └─Linear: 2-3                       [100, 1]                  4
│    └─Sigmoid: 2-4                      [100, 1]                  --
Total params: 37
Trainable params: 37
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01
