<a href="https://colab.research.google.com/github/sanchi23002/pytorch_projects_/blob/main/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


np ---> torch
array ---> tensor

In [ ]:
if torch.cuda. is_available():
  print("GPU is available")
  print("GPU NAME IS ",torch.cuda.get_device_name(0))
else:
  print("GPU is not available")

GPU is available
GPU NAME IS  Tesla T4


In [ ]:
#USING EMPTY
a = torch.empty(2,3)# assign place in memory and show value of that spaces as it is
print(a)
print(type(a))

tensor([[0.0000e+00, 1.6255e-43, 7.7052e+31],
        [1.9447e+31, 2.1715e-18, 2.3081e-12]])
<class 'torch.Tensor'>


In [ ]:
# USING ZEROS
b = torch.zeros(2,3, dtype = torch.int32)
print(b)
c = torch.zeros(2,3)
print(c,"  ",type(c),"  ", c.dtype)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])    <class 'torch.Tensor'>    torch.float32


In [ ]:
# USING ONES
d = torch.ones(2,3, dtype = torch.int32)
print(d,"  ", torch.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)    <class 'torch.dtype'>


In [ ]:
# USING FULL
j = torch.full((2,3),10)
print(j)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [ ]:
#using rand  (give numbers between (0,1))
torch.rand(2,3, dtype=torch.float16)

tensor([[0.1685, 0.7422, 0.3975],
        [0.4224, 0.0024, 0.8135]], dtype=torch.float16)

In [ ]:
# USING TENSOR
f = torch.tensor([[1,2,3,4],[3,4,5,6]],dtype = torch.float32)
print(f)

tensor([[1., 2., 3., 4.],
        [3., 4., 5., 6.]])


In [ ]:
g = torch.arange(1,11)  ## (start , stop , step)
print(g)
h = g.reshape(5,2)
print(h)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [ ]:
# by using linspace  (linearly placed)
torch.linspace(0,100,11) # (start(inc.), stop(inc.), number of element)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# USING EYE (FOR MAKING IDENTITY MATRIX)
k = torch.eye(10, dtype = torch.int32)
print(k)
print(k.shape)
print(k.dtype)

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=torch.int32)
torch.Size([10, 10])
torch.int32


In [ ]:
#FOR MAKING SAME SHAPE
l = torch.zeros_like(f)
print(l)
l2 = torch.empty_like(h)
print(l2)
l3 = torch.full_like(d,8)
print(l3)
l4 = torch.rand_like(a,dtype = torch.float32)
print(l4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[        0, 193170560],
        [        0,         0],
        [        1,         1],
        [        0,         0],
        [        0,         0]])
tensor([[8, 8, 8],
        [8, 8, 8]], dtype=torch.int32)
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [ ]:
int_l = l.to(torch.int32)
print(int_l)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


SCALER OPERATIONS

In [ ]:
a1 = f+2
a2 = f-2
a3 = f*500
a4 = f/5##(normal devision)
a5 = a3//5 ##(integer devision)
print(f"{a1}\n\n  {a2}\n\n  {a3}\n\n  {a4} \n\n {a5}")

tensor([[3., 4., 5., 6.],
        [5., 6., 7., 8.]])

  tensor([[-1.,  0.,  1.,  2.],
        [ 1.,  2.,  3.,  4.]])

  tensor([[ 500., 1000., 1500., 2000.],
        [1500., 2000., 2500., 3000.]])

  tensor([[0.2000, 0.4000, 0.6000, 0.8000],
        [0.6000, 0.8000, 1.0000, 1.2000]]) 

 tensor([[100., 200., 300., 400.],
        [300., 400., 500., 600.]])


In [ ]:
x = torch.tensor([[2,3,4],[5,6,7]])
z = torch.tensor([[1,2,4],[8,7,9]])
y = torch.tensor([[100,200,300],[587,699,800]])
print(x,"\n\n\n",y)
print("\n\n")
print(x+y)
print("\n\n")
print(x-y)
print("\n\n")
print(x*y)
print("\n\n")
print(y//x)
print("\n\n")
print(y/x)
print("\n\n")
print(x**z)

tensor([[2, 3, 4],
        [5, 6, 7]]) 


 tensor([[100, 200, 300],
        [587, 699, 800]])



tensor([[102, 203, 304],
        [592, 705, 807]])



tensor([[ -98, -197, -296],
        [-582, -693, -793]])



tensor([[ 200,  600, 1200],
        [2935, 4194, 5600]])



tensor([[ 50,  66,  75],
        [117, 116, 114]])



tensor([[ 50.0000,  66.6667,  75.0000],
        [117.4000, 116.5000, 114.2857]])



tensor([[       2,        9,      256],
        [  390625,   279936, 40353607]])


In [ ]:
# GETTING ABSOLUTE VALUE OF TENSOR
n = torch.tensor([-1,-2,-4,6])
n_abs = torch.abs(n)
print(n_abs)

tensor([1, 2, 4, 6])


In [ ]:
# GETTING NEGATIVE VALUE OF TENSOR
n_neg = torch.neg(n)
print(n_neg)

tensor([ 1,  2,  4, -6])


In [ ]:
# rounding the numbers in tensor
m = torch.tensor([1.34,1.77,1.5])
m_round = torch.round(m)
print(m_round)

tensor([1., 2., 2.])


In [ ]:
##  (ceil)  returns the smallest integer that is greater than or equal to the original value
n = torch.tensor([1.34, 1.77 , 1.5])
n_ceil = torch.ceil(n)
print(n_ceil)

tensor([2., 2., 2.])


In [ ]:
##  (floor) returns the largest integer that is less than or equal to the original value.
n_floor = torch.floor(n)
print(n_floor)

tensor([1., 1., 1.])


In [ ]:
## (clamp) ---> camlp the value of the tensor
v = torch.tensor([[2,5,8],[5.7,6.6,9]])
v_clamp = torch.clamp(v, min=5, max =8)
print(v)
print(v_clamp)

tensor([[2.0000, 5.0000, 8.0000],
        [5.7000, 6.6000, 9.0000]])
tensor([[5.0000, 5.0000, 8.0000],
        [5.7000, 6.6000, 8.0000]])


 **reduction** **operation**

In [ ]:
w = torch.randint(size=(2,4),low = 2, high = 10)
print(w)

tensor([[2, 9, 5, 3],
        [6, 2, 9, 4]])


In [ ]:
print(w.sum())
print(w.sum(dim=0))## along column (a11+a21)
print(w.sum(dim=1))## along row sum (a11+a12+a13+a14)

tensor(40)
tensor([ 8, 11, 14,  7])
tensor([19, 21])


In [ ]:
w = torch.tensor([[2,4,5],[6,7,9]])
w = w.to(torch.float32)
torch.mean(w)## mean work only on float datatype
torch.median(w)
print(torch.mean(w))
print(torch.median(w))
print(torch.std(w))
print(torch.var(w))
print(torch.prod(w))
print(torch.max(w,dim =0))

tensor(5.5000)
tensor(5.)
tensor(2.4290)
tensor(5.9000)
tensor(15120.)
torch.return_types.max(
values=tensor([6., 7., 9.]),
indices=tensor([1, 1, 1]))


In [ ]:
## returns the indices (positions) of the maximum values in a tensor
print(torch.argmax(w))

tensor(5)


In [ ]:
## MATRIX MULTIPLICATION
ten1 = torch.tensor([[1,3,5],[6,7,8]])
ten2 = torch.tensor([[4,5,6,11],[8,9,7,12],[1,1,2,3]])
ten_res = torch.matmul(ten1,ten2)
print(ten_res)

tensor([[ 33,  37,  37,  62],
        [ 88, 101, 101, 174]])


In [ ]:
## vector dot product
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])
vec_res = torch.dot(vec1,vec2)
print(vec_res)

tensor(32)


In [ ]:
## transpose of matrix
vec3 = torch.transpose(ten1, 0, 1)
print(vec3)

tensor([[1, 6],
        [3, 7],
        [5, 8]])


In [ ]:
## determinant
ten4 = torch.tensor([[1,2,3],[4,5,6],[7,8,9.9]], dtype = torch.float32)## must contain one floating point
print(torch.det(ten4))

tensor(-2.7000)


In [ ]:
## inverse of a matrix
ten5 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype = torch.float32)
print(torch.inverse(ten5))

tensor([[ -2796203.5000,   5592406.0000,  -2796203.5000],
        [  5592405.0000, -11184812.0000,   5592407.0000],
        [ -2796201.7500,   5592406.0000,  -2796203.5000]])


In [ ]:
print(torch.sqrt(ten5)) ## square root
print(torch.pow(ten5, 2))
print(torch.log(ten5))
print(torch.log2(ten5))
print(torch.log10(ten5))
print(torch.exp(ten5))

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495],
        [2.6458, 2.8284, 3.0000]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918],
        [1.9459, 2.0794, 2.1972]])
tensor([[0.0000, 1.0000, 1.5850],
        [2.0000, 2.3219, 2.5850],
        [2.8074, 3.0000, 3.1699]])
tensor([[0.0000, 0.3010, 0.4771],
        [0.6021, 0.6990, 0.7782],
        [0.8451, 0.9031, 0.9542]])
tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])


In [ ]:
## we can use relu , sigmoid function also in a tensor
ten6 = torch.tensor([[1,-2,3],[-4,5,6],[7,8,-9]], dtype = torch.float32)
print(torch.sigmoid(ten6)) ## z = 1/(1+e^-x)
print(torch.relu(ten6)) ## z= max(0,x)

tensor([[7.3106e-01, 1.1920e-01, 9.5257e-01],
        [1.7986e-02, 9.9331e-01, 9.9753e-01],
        [9.9909e-01, 9.9966e-01, 1.2339e-04]])
tensor([[1., 0., 3.],
        [0., 5., 6.],
        [7., 8., 0.]])


In [ ]:
##  Directly modifies the data of tensor m by adding n to it. It returns the updated m without allocating new memory
vec1.add_(vec2)
print(vec1)

tensor([5, 7, 9])


**INPLACE FUNCTIONS** tensor_name.func_(nothing if one func. work, else the other function)

In [6]:
ten1 = torch.tensor([[1,2,3],[5,6,7]], dtype = torch.float32)
w = torch.tensor([[0.5,0.4,0.44],[0.11,0.22,0.33]])
print(w)
print("\n\n")
ten1.mul_(w) ## prod and sum are reduction formula for one matrix
print(ten1)
print("\n\n")
ten1.relu_()
print(ten1)

tensor([[0.5000, 0.4000, 0.4400],
        [0.1100, 0.2200, 0.3300]])



tensor([[0.5000, 0.8000, 1.3200],
        [0.5500, 1.3200, 2.3100]])



tensor([[0.5000, 0.8000, 1.3200],
        [0.5500, 1.3200, 2.3100]])


In [7]:
## 1. To know the place of a tensor in the memory
d = ten1 ##Assignment operator doesn't make a new tensor. It just makes a new pointer that points at the same tensor,
## which is allocated in memory. When you change the main tensor, TAN1 is automatically changed by itself.
print(id(d))
print(id(ten1))

135202245411936
135202245411936


In [8]:
## We don't want that in our copy, the changes occur, which we are done in the actual tensor, so for that we use clone.
c = torch.clone(ten1)
ten1[1,2]= 45
print(ten1)
print(c)
print(id(c))
print(id(ten1))

tensor([[ 0.5000,  0.8000,  1.3200],
        [ 0.5500,  1.3200, 45.0000]])
tensor([[0.5000, 0.8000, 1.3200],
        [0.5500, 1.3200, 2.3100]])
135201910161568
135202245411936


In [9]:
torch.cuda.is_available()

True

In [11]:
device = torch.device("cuda")

In [12]:
f = torch.rand((2,4), device = device)
print(f)

tensor([[0.9423, 0.1517, 0.0571, 0.6160],
        [0.2721, 0.6029, 0.7173, 0.4303]], device='cuda:0')


In [13]:
ten1.to(device)

tensor([[ 0.5000,  0.8000,  1.3200],
        [ 0.5500,  1.3200, 45.0000]], device='cuda:0')

Reshape operations

In [32]:
x = torch.arange(1,31)
print(x)
y=x.reshape(5,3,2)
print(y)
z = torch.flatten(y)
print(z)
## permute --> to arrage the shape again
g=y.permute(2,1,0)
print(g.shape)
print(g)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])
torch.Size([2, 3, 5])
tensor([[[ 1,  7, 13, 19, 25],
         [ 3,  9, 15, 21, 27],
         [ 5, 11, 17, 23, 29]],

        [[ 2,  8, 14, 20, 26],
         [ 4, 10, 16, 22, 28],
         [ 6, 12, 18, 24, 30]]])


In [39]:
## unsqueeze--> This is used to add dimension in your wanted place in a tensor.
j=torch.unsqueeze(g,2)
print(j.shape)

torch.Size([2, 3, 1, 5])


In [43]:
## Squeeze is used to remove any dimension from a tensor.
j=torch.squeeze(g,2)
print(j.shape)
k = g.squeeze(0)
print(k.shape)
print(k)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])
tensor([[[ 1,  7, 13, 19, 25],
         [ 3,  9, 15, 21, 27],
         [ 5, 11, 17, 23, 29]],

        [[ 2,  8, 14, 20, 26],
         [ 4, 10, 16, 22, 28],
         [ 6, 12, 18, 24, 30]]])


In [10]:
## Converting numpy array into tensor and tensor into numpy array
import numpy as np
a = torch.tensor([1,2,3,4,5])
print(a)
b = a.numpy()
print(b)
print(type(b))
c = torch.from_numpy(b)
print(c)
print(type(c))

tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
